[project]
name = "neurometa"
version = "2.0.0"
description = "Package for generating metadata related to neuroscience"
authors = [
    { name = "Can H. Tartanoglu", email = "canhtart@gmail.com" }
]
maintainers = [
    { name = "Can H. Tartanoglu", email = "canhtart@gmail.com" }
]
license = { text = "BSD-3-Clause" }
readme = "README.md"
requires-python = ">=3.12,<4.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"
]
dependencies = [
    "pydantic>=2",
    "pandas[compression,parquet,excel]",
    "deepdiff>=8.6",
    "Wikipedia-API>=0.5.4"
]

[project.urls]
repository = "https://github.com/memorycircuits/neurometa"

[build-system]
requires = ["uv_build>=0.8.23,<0.9.0"]
build-backend = "uv_build"
